import ROOT
from ROOT import TCanvas, TFile, TProfile, TNtuple, TH1I, TH1F, TH2F, TH3F, TColor, TEfficiency
from ROOT import gROOT, gBenchmark, gRandom, gSystem
import numpy as np
import pdb

gROOT.LoadMacro("sPhenixStyle.C");
gROOT.ProcessLine("SetsPhenixStyle()")

topo_thres = ['-9999','0','100','200','300','500']
thres_string = ['All E_{topo}','E_{topo} > 0 MeV','E_{topo} > 100 MeV','E_{topo} > 200 MeV','E_{topo} > 300 MeV','E_{topo} > 500 MeV']

f2 = ROOT.TFile.Open("output_pu_correct_ana509_v2_dijet_bkg_cut.root")
h_ue_towards = TH1F(f2.Get("h_ue_towards"))
h_ue_transverse = TH1F(f2.Get("h_ue_transverse"))
h_ue_away = TH1F(f2.Get("h_ue_away"))
h_ue_towards.Rebin(2)
h_ue_transverse.Rebin(2)
h_ue_away.Rebin(2)
h_ue_towards.Scale(1.0/h_ue_towards.Integral())
h_ue_transverse.Scale(1.0/h_ue_transverse.Integral())
h_ue_away.Scale(1.0/h_ue_away.Integral())
h_ue_towards.SetDirectory(0)
h_ue_transverse.SetDirectory(0)
h_ue_away.SetDirectory(0)
h_ue_pt_towards = TProfile(f2.Get("h_ue_pt_towards"))
h_ue_pt_transverse = TProfile(f2.Get("h_ue_pt_transverse"))
h_ue_pt_away = TProfile(f2.Get("h_ue_pt_away"))
h_ue_pt_towards.SetDirectory(0)
h_ue_pt_transverse.SetDirectory(0)
h_ue_pt_away.SetDirectory(0)
h_ue_pt_transverse_thres = []
for i, t in enumerate(topo_thres):
    h_ue_pt_transverse_thres.append(TProfile(f2.Get("h_sume_topo"+t+"_ue_pt_transverse")))
    h_ue_pt_transverse_thres[i].SetDirectory(0)
f2.Close()

f2 = ROOT.TFile.Open("output_sim_dijet_bkg_cut_28.root")
h_mc_ue_towards = TH1F(f2.Get("h_ue_towards"))
h_mc_ue_transverse = TH1F(f2.Get("h_ue_transverse"))
h_mc_ue_away = TH1F(f2.Get("h_ue_away"))
h_mc_ue_towards.Rebin(2)
h_mc_ue_transverse.Rebin(2)
h_mc_ue_away.Rebin(2)
h_mc_ue_towards.Scale(1.0/h_mc_ue_towards.Integral())
h_mc_ue_transverse.Scale(1.0/h_mc_ue_transverse.Integral())
h_mc_ue_away.Scale(1.0/h_mc_ue_away.Integral())
h_mc_ue_towards.SetDirectory(0)
h_mc_ue_transverse.SetDirectory(0)
h_mc_ue_away.SetDirectory(0)
h_mc_ue_pt_towards = TProfile(f2.Get("h_ue_pt_towards"))
h_mc_ue_pt_transverse = TProfile(f2.Get("h_ue_pt_transverse"))
h_mc_ue_pt_away = TProfile(f2.Get("h_ue_pt_away"))
h_mc_ue_pt_towards.SetDirectory(0)
h_mc_ue_pt_transverse.SetDirectory(0)
h_mc_ue_pt_away.SetDirectory(0)
h_mc_ue_pt_transverse_thres = []
for i, t in enumerate(topo_thres):
    h_mc_ue_pt_transverse_thres.append(TProfile(f2.Get("h_sume_topo"+t+"_ue_pt_transverse")))
    h_mc_ue_pt_transverse_thres[i].SetDirectory(0)
f2.Close()


t_canvas = ROOT.TCanvas("t_canvas","",600,600)
t_tex = ROOT.TLatex(0.2, 0.88, "#bf{#it{sPHENIX}} Internal")
t_tex.SetNDC() # Set coordinates relative to the pad (0 to 1)
t_tex.SetTextSize(0.04)
t_tex1 = ROOT.TLatex(0.2, 0.83, "200 GeV p+p Towards Region Topoclusters")
t_tex1.SetNDC() # Set coordinates relative to the pad (0 to 1)
t_tex1.SetTextSize(0.04)
t_leg = ROOT.TLegend(.5,.65,.92,.75)
t_leg.AddEntry(h_ue_towards,"Data","pl")
t_leg.AddEntry(h_mc_ue_towards,"Pythia8 + Geant4","pl")
h_ue_towards.SetStats(0)
h_mc_ue_towards.SetStats(0)
h_mc_ue_towards.SetLineColor(ROOT.kBlue+1)
h_mc_ue_towards.SetMarkerColor(ROOT.kBlue+1)
h_mc_ue_towards.SetMarkerStyle(24)
h_ue_towards.GetXaxis().SetRangeUser(0,14)
h_ue_towards.GetYaxis().SetRangeUser(0.00001,2)
h_ue_towards.Draw()
h_ue_towards.SetXTitle("#SigmaE_{T}/#delta#eta#delta#phi [GeV]") 
h_ue_towards.SetYTitle("1/N dN/d(#SigmaE_{T}/#delta#eta#delta#phi) [GeV^{-1}]") 
h_mc_ue_towards.Draw('same')
t_canvas.SetLogy(1)
t_leg.SetTextSize(0.04)
t_leg.Draw()
t_tex.Draw("same")
t_tex1.Draw("same")
t_canvas.Draw()
t_canvas.SaveAs("figure4_h_et_towards_topo_paper.pdf")

tr_canvas = ROOT.TCanvas("tr_canvas","",600,600)
tr_tex = ROOT.TLatex(0.2, 0.88, "#bf{#it{sPHENIX}} Internal")
tr_tex.SetNDC() # Set coordinates relative to the pad (0 to 1)
tr_tex.SetTextSize(0.04)
tr_tex1 = ROOT.TLatex(0.2, 0.83, "200 GeV p+p Transverse Region Topoclusters")
tr_tex1.SetNDC() # Set coordinates relative to the pad (0 to 1)
tr_tex1.SetTextSize(0.04)
tr_leg = ROOT.TLegend(.5,.65,.92,.75)
tr_leg.AddEntry(h_ue_transverse,"Data","pl")
tr_leg.AddEntry(h_mc_ue_transverse,"Pythia8 + Geant4","pl")
h_ue_transverse.SetStats(0)
h_mc_ue_transverse.SetStats(0)
h_mc_ue_transverse.SetLineColor(ROOT.kBlue+1)
h_mc_ue_transverse.SetMarkerColor(ROOT.kBlue+1)
h_mc_ue_transverse.SetMarkerStyle(24)
h_ue_transverse.GetXaxis().SetRangeUser(-1,5)
h_ue_transverse.GetYaxis().SetRangeUser(0.00001,7)
h_ue_transverse.Draw()
h_ue_transverse.SetXTitle("#SigmaE_{T}/#delta#eta#delta#phi [GeV]") 
h_ue_transverse.SetYTitle("1/N dN/d(#SigmaE_{T}/#delta#eta#delta#phi) [GeV^{-1}]") 
h_mc_ue_transverse.Draw('same')
tr_canvas.SetLogy(1)
tr_leg.SetTextSize(0.04)
tr_leg.Draw()
tr_tex.Draw("same")
tr_tex1.Draw("same")
tr_canvas.Draw()
tr_canvas.SaveAs("figure4_h_et_transverse_topo_paper.pdf")

a_canvas = ROOT.TCanvas("a_canvas","",600,600)
a_tex = ROOT.TLatex(0.2, 0.88, "#bf{#it{sPHENIX}} Internal")
a_tex.SetNDC() # Set coordinates relative to the pad (0 to 1)
a_tex.SetTextSize(0.04)
a_tex1 = ROOT.TLatex(0.2, 0.83, "200 GeV p+p Away Region Topoclusters")
a_tex1.SetNDC() # Set coordinates relative to the pad (0 to 1)
a_tex1.SetTextSize(0.04)
a_leg = ROOT.TLegend(.5,.65,.92,.75)
a_leg.AddEntry(h_ue_away,"Data","pl")
a_leg.AddEntry(h_mc_ue_away,"Pythia8 + Geant4","pl")
h_ue_away.SetStats(0)
h_mc_ue_away.SetStats(0)
h_mc_ue_away.SetLineColor(ROOT.kBlue+1)
h_mc_ue_away.SetMarkerColor(ROOT.kBlue+1)
h_mc_ue_away.SetMarkerStyle(24)
h_ue_away.GetXaxis().SetRangeUser(0,12)
h_ue_away.GetYaxis().SetRangeUser(0.00001,2)
h_ue_away.Draw()
h_ue_away.SetXTitle("#SigmaE_{T}/#delta#eta#delta#phi [GeV]") 
h_ue_away.SetYTitle("1/N dN/d(#SigmaE_{T}/#delta#eta#delta#phi) [GeV^{-1}]") 
h_mc_ue_away.Draw('same')
a_canvas.SetLogy(1)
a_leg.SetTextSize(0.04)
a_leg.Draw()
a_tex.Draw("same")
a_tex1.Draw("same")
a_canvas.Draw()
a_canvas.SaveAs("figure4_h_et_away_topo_paper.pdf")
