executable = MBDEfficiencyJet.sh
arguments = 0 $(Process) 0 mbd_eff_list_files/dst_calofitting_runlist_1.txt mbd_eff mbd_eff_list_files/dst_trkr_tracks_runlist_1.txt mbd_eff_list_files/dst_trkr_seed_runlist_1.txt mbd_eff_list_files/dst_trkr_cluster_runlist_1.txt
output = output_logs/output_mbd_eff1_$(Process).out
request_memory = 12GB
when_to_transfer_output = ON_EXIT
error			= output_logs/error_mbd_eff1_$(Process).err
log = /tmp/egm2153_1_$(Process).log
queue 9262
